const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  companyLogo: state => state.user.companyLogo,
  companyName: state => state.user.companyName,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  abilities: state => state.permission.abilities,
  meta: state => state.permission.meta,
  isget: state => state.user.isget,
  notification: state => state.user.notification,
  companyId: state => state.user.companyId,
  company: state => state.user.company
}
export default getters
